// <auto-generated />
namespace OmegaInc.VagasEmprego.CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class finalCidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finalCidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291258531_finalCidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
